# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CodeCamp 2018
topline: CodeCamp 2018
welcome: Welcome to Human Aid CodeCamp 2018
tagline: A codecamp on theme "Human AID"
date: 18-20 July, 2018
email: codecamp2018@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  <b>Innovative Computer Engineering Students’ Society (iCES)</b> and <b>Club of Technical Students (CoTS)</b> 
  are organizing a CodeCamp with the theme “Human Aid” on the occasion of technical festival held
  in Paschimanchal Campus on the pre-scheduled date. This event will make use of Information 
  Technology to build and innovate applicable systems with the brainstorming of ideas to
  solve real-world problems.
more_about: >-
  CodeCamp 2018 is a 3 days event on theme “Human Aid” focusing on the development of innovative
  solutions to address the problems faced by differently abled people. The event  aims to attract
  most energetic, talented and vibrant youths from all around the country to compete with one 
  another to develop the most elegant solution. The participants will brainstorm, code  and create
  a working prototype within the event time. Participants are selected through a rigorous 
  application process. They are required to submit their ideas by Asar 20. Registration fee
  for each team is Rs. 1500. Only the team with selected idea is eligible for participating 
  in the CodeCamp and needs to register for the event. 
participation_text: >-
  Participants are selected through a rigorous application process. 
  They are required to submit their ideas by Asar 23. Entry fee 
  for each team is Rs. 1500. 
  Only the teams with selected idea are eligible for participating in the CodeCamp and needs to register for the event.
  The result of seleted teams will be posted in Asar 26.
registeration_text: >-
  Team (3 members at max and 2 at min) must register their team names for “CodeCamp” with 
  entry fee Rs.1500 (includes lunch set).
  Every Team member must provide 2 passport size photos to the coordinator. 

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: codecamp2018
github_username:  jekyll
email: contact@codecamp2018.com
register_email: register@codecamp2018.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
