# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Genese CodeCamp 2018
topline: Genese CodeCamp 2018
welcome: Welcome to Genese CodeCamp 2018
tagline: A codecamp on theme "Human AID"
date: 18-20 July, 2018
email: codecamp2018@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  With joint efforts of<b> Club of Technical Students (CoTS)</b> and <b>Innovative Computer Engineering Students’ Society (iCES)</b>,
  a themed <b>CodeCamp</b> is taking place from July 18-20 in the premises of Paschimanchal Campus, Lamachaur, Pokhara. The theme selected
  for this year is ‘Human Aid’ referring to any human assistance through technology – be it software, hardware or a subtle combination
  of both. This CodeCamp is organized on the occasion of a technical festival Vector-Direct Your Vision whose major objective is to
  brainstorm ideas, build and innovate systems and apply them to solve real-life problems.
more_about: >-
  CodeCamp 2018 is a three-day event entirely focused on developing and promoting appropriate, innovative solutions,
  especially to address the needs and problems faced by differently abled people. Participants are selected through a
  rigorous selection process based on the ideas they submit [the idea submission deadline is 27th Asar (i.e. 11th July).
  The selected participants are then required to register for the event with the registration fee of NRs. 1500. During the event,
  the participants are expected to further brainstorm their selected ideas, code and create a working prototype and pitch their ideas
  in the span of three days.
participation_text: >-
  Participants are selected through a rigorous application process. 
  They are required to submit their ideas by Asar 27. Entry fee 
  for each team is Rs. 1500. 
  Only the teams with selected idea are eligible for participating in the CodeCamp and needs to register for the event.
  The result of selected teams will be posted in Asar 26.
registeration_text: >-
  Team (3 members at max and 2 at min) must register their team names for “CodeCamp” with 
  entry fee Rs.1500.
  Every Team member must provide 2 passport size photos to the coordinator. 

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: codecamp2018
github_username:  jekyll
email: contact@codecamp2018.com
register_email: register@codecamp2018.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
